modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GNU LGPL 3.0"

[[mods]]
modId = "blockprivacy"
version = "${version}"
displayName = "BlockPrivacy"
authors = "LuzFaltex Contributors"
description = '''
Open source block library for securing blocks like doors and chests.
'''
#logoFile = ""

[[dependencies.blockprivacy]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockprivacy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockprivacy]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
